// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

// Mod
archives_base_name=Cauldron-Pipes
mod_group_id=acidglow.cauldron_pipes
mod_id=cauldron_pipes
mod_version=26.1.0.001
mod_name=Cauldron-Pipes
mod_description=Connect pipes to cauldrons.
mod_license=MIT
mod_homepage=https://github.com/Acidglow/Cauldron-Pipes
mod_source=https://github.com/Acidglow/Cauldron-Pipes.git
mod_issues=https://github.com/Acidglow/Cauldron-Pipes/issues

// Minecraft, Mod Loader
minecraft_version=26.1
minecraft_version_range=[26.1]
neo_version=26.1.0.19-beta
neogradle.subsystems.conventions.sourcesets.enabled=false
